version: "3"
services:
  linter:
    image: bufbuild/buf:latest
    container_name: money-buf-linter
    working_dir: /app
    command:
      - lint
    volumes:
      - .:/app
  breaking:
    image: bufbuild/buf:latest
    container_name: money-buf-breaking
    entrypoint: /bin/sh
    working_dir: /app
      - /bin/sh
      - -c
      - |
      git config --global --add safe.directory /app/.git &&
      buf breaking --against '.git#branch=master'
    volumes:
      - .:/app
  generator:
    image: skydev/proto-gen-b:6.0.0
    container_name: money-proto-gen
    working_dir: /app
    depends_on:
      - linter
      - breaking
    entrypoint: /root/go/bin/buf
    command:
      - generate
    volumes:
      - .:/app
  mocks:
    depends_on:
      - generator
    image: skydev/proto-gen-b:6.0.0
    container_name: money-mocks
    entrypoint: /bin/bash
    command:
      - ./mocks.sh
    volumes:
      - .:/app
    working_dir: /app
